### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ss880426** [AKASH2907/deepfakes_video_classification#11]
I used 08.facenet_embeddings.py but ran out of this error
urllib.error.HTTPError: HTTP Error 404: Not Found
How to solve this?
thanks

**Comment by ss880426** [comment]
solved it 
thanks

**Comment by ss880426** [comment]
Sorry, I got this error when I run python 09.train_triplets_semi_hard.py, how can I fix it?
ValueError: Error when checking input: expected input_image to have 2 dimensions, but got array with shape (40887, 1, 512)

**Comment by AKASH2907** [comment]
Use torch squeeze to squeeze the first dimension

**Comment by ss880426** [comment]
thank you!!
