### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mamarasulovs** [AKASH2907/deepfakes_video_classification#16]
If we download only 1 dataset for example forencisface ++ and also available for this project? And which part of the project I have to put my data? Should I open a new folder into project?

**Comment by AKASH2907** [comment]
I guess this code [Link](https://github.com/AKASH2907/deepfakes_video_classification/blob/master/00.train_data_prepare.py) explains everything you asked. I looked into NeuralTextures dataset. I don't remember the exact directory structure inside that. I created npy files that can be kept anywhere. The main folder is fine as well.

I don't see any issues as such from a dataset creation point of view. Closing this issue. If it's still not clear, please feel free to open the issue.
