### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by zia7** [AKASH2907/deepfakes_video_classification#3]
Hi I am facing this error while running train_cnn.py file here is the error https://imgur.com/a/PjvRQFE please guide me to resolve this. Thank you

**Comment by AKASH2907** [comment]
Does your version matches as its mentioned on the readme page? I had TF version 1.14.0 and Keras 2.3.0?

**Comment by zia7** [comment]
I am using TF 2.2.0 Let me check with 1.14.0

**Comment by zia7** [comment]
Thank you this error is resolved training has been started I will update you if any error occur. Thank you for your response.

**Comment by AKASH2907** [comment]
I'm closing this issue then.
