### ISSUE TITLE
Batches Dimension Issue 

### ISSUE THREAD

**Issue by zia7** [AKASH2907/deepfakes_video_classification#4]
Can you please guide me regarding Batches Dimension issue as I am facing while running evaluate_CNN.py. when I print batches shape I get (0,). I have also tried batches=np.reshape(1,160,160,3) but didn't work

error: https://imgur.com/a/bIvQhDk

**Comment by AKASH2907** [comment]
I have modified the code. Run it again.

**Comment by zia7** [comment]
Still facing the same issue. If you want me to run specific line of code to debug please let me know I will share the result.

**Comment by AKASH2907** [comment]
Your test_vids.csv looks something like this, right?

vids_list | label
-- | --
test_c23/0/612_702.mp4 | 0
test_c23/1/720.mp4 | 1
test_c23/0/823_584.mp4 | 0

and the path directly reads the video?
Bcz same code runs fine in my system

**Comment by zia7** [comment]
when I run data_csv there was no folder name of train_path = ["train_faces_all/1", "train_faces_all/0"]
so I replace it with train_path = ["train_face/1", "train_face/0"] train_face folder was created by face_extraction and my csv file was created. I hope I have done this correctly. The above error was because of colab path issues I figured that out and also turned on GPU runtime

![saq](https://user-images.githubusercontent.com/65252065/81929085-cc990180-95ff-11ea-8661-657b837e8c84.png)


In the next step when I run train_c3D.py following error is coming in colab

ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

![wsx](https://user-images.githubusercontent.com/65252065/81929438-711b4380-9600-11ea-87c0-e20daf6c2187.png)

**Comment by AKASH2907** [comment]
I have some paper deadlines. I'll try to update whole repo by weekend. I'll look into the error.

**Comment by AKASH2907** [comment]
I have updated till LSTM. I'll update triplets in a little more time. If you face any errors amongst those, report me, I'll try to fix it.

(I have some conf deadline)

**Comment by zia7** [comment]
I have tried the updated file the issue I am facing is with 03.trainc3D.py. My data is 40 real videos and 40 fake videos with

print(len(train_vid_list))= 65
print(len(val_vid_list))=17

!python 03.train_C3D.py -e 15 -w weights_c3d -m c3d -b 32 #not working
!python 03.train_C3D.py -e 10 -w weights_c3d -m c3d -b 16 #not working

with following commands I am facing this error can you please guide regarding this

![err](https://user-images.githubusercontent.com/65252065/82736293-fd84df00-9d41-11ea-815c-e9016135667e.png)


![err2](https://user-images.githubusercontent.com/65252065/82736313-358c2200-9d42-11ea-886d-1c52ad3f6eda.png)


I think the issue might be with the batch size function generator_val_batch

**Comment by AKASH2907** [comment]
Rectified it.

**Comment by zia7** [comment]
Do you have any idea regarding this issue in 05_lstm_feature i have tried for xception and ef0 both having same issue

![ee](https://user-images.githubusercontent.com/65252065/82740907-76962d80-9d66-11ea-8eed-7a8b8d23c18d.png)

**Comment by AKASH2907** [comment]
I have edited that code file.

**Comment by zia7** [comment]
In the last part 07 evaluate CNN LSTM the error is related to fc1 do you think is it related to weights trained (in my case xception_best.hdf5) or there is any other issue which I might be missing or needs to be checked

I think my xception weights have 81 layers

![ere](https://user-images.githubusercontent.com/65252065/82972184-dbaf8480-9fed-11ea-8998-6ccb641b367b.png)

**Comment by AKASH2907** [comment]
It's not with that, layer name is to be mentioned. If you go thru lstm_features, you will find out. I'll update the remaining codes in a bit.

**Comment by AKASH2907** [comment]
Updated the evaluation cnn lstm code.
